name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Build Celeste Dashboard
        run: yarn build
      - name: Run BundleWatch
        run: yarn bundlewatch
    env:
      CI: true
      BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
